### ISSUE TITLE
isContainer removes whitespaces from the input parameter

### ISSUE THREAD

**Issue by artfwo** [ruanmartinelli/is-container#1]
isContainer returns true if a whitespace is present in the input parameter. Consider the following cases:
```
isContainer('MSKU6011672 ')
isContainer(' MSKU6011672 ')
isContainer('MSK U60 11672')
```
This makes it impossible to use isContainer to validate e.g. user input, because it will silently return true for all of the above.

**Comment by ruanmartinelli** [comment]
Hi! Sorry for the late reply.

Do you know if ISO 6346 is strict about the use of white spaces, hyphens, etc?

If so, we can consider a `{ strict: true }` options parameter as a second argument and include that verification. Otherwise we'd have to create our own rule, which sort of misses the point of validating against a spec.

**Comment by artfwo** [comment]
Agreed. I don't think ISO has any whitespace regulations covering digital container numbers though.

But even if having whitespaces in container number is okay, it does make sense to enforce whitespace trimming to be more explicit (i.e. `s.trim(); isContainer(s))`, doesn't it?

**Comment by ruanmartinelli** [comment]
You have a point, @artfwo. 

Do you have anything specific in mind for a solution? We can take this discussion to a PR and work on this together. If not, I'll start one myself in the near future.

**Comment by artfwo** [comment]
Yeah, my suggestion is not to remove whitespaces, so the library user has to do it explicitly.
